import streamlit as st
import pandas as pd
import numpy as np
import requests
import folium
from streamlit_folium import st_folium
import datetime

# --- PAGE CONFIGURATION ---
st.set_page_config(
    page_title="Quantum Grid Node",
    page_icon="🔮",
    layout="wide"
)

st.title("🔮 Project Unified Field: Universal Geometries & RSPK Engine")
st.markdown("Mapping universal space-time anomalies, poltergeist RSPK vectors, and geometric time collapse curves.")

# --- LIVE METRIC FETCH ENGINES ---
def get_lunar_gravitational_factor():
    now = datetime.datetime.now()
    diff = now - datetime.datetime(2026, 1, 1)
    days = diff.days + (diff.seconds / 86400.0)
    cycle_position = (days % 29.53) / 29.53
    illumination = 0.5 * (1 - np.cos(2 * np.pi * cycle_position))
    gravitational_pull = 1.0 + (0.35 * np.abs(np.sin(np.pi * cycle_position)))
    return round(illumination * 100, 1), round(gravitational_pull, 2)

@st.cache_data(ttl=3600)
def get_live_celestial_kp():
    noaa_endpoint = "https://noaa.gov"
    try:
        response = requests.get(noaa_endpoint, timeout=5)
        if response.status_code == 200:
            data = response.json()
            live_kp = float(data.get("0", {}).get("geomagnetic", {}).get("scale", 2.0)) * 2.0
            return max(1.0, min(9.0, live_kp))
    except Exception:
        pass
    return 3.0

lunar_illumi, lunar_grav = get_lunar_gravitational_factor()
live_kp = get_live_celestial_kp()

# --- SIDEBAR CONTROL PANEL ---
st.sidebar.header("🌍 Global Coordinate Focal Array")
mode = st.sidebar.selectbox(
    "Select Target Spatial Matrix",
    ["Skinwalker Ranch (Utah, USA)", "Stonehenge (Wiltshire, UK)", "The Great Pyramid (Giza, Egypt)", "The Paris Catacombs (Paris, France)", "Universal Custom Coordinates Shift"]
)

# Set base parameters based on selection
if mode == "Skinwalker Ranch (Utah, USA)":
    user_lat, user_lon, target_name, base_imprint, tectonic_strain = 40.2592, -109.8885, "Skinwalker Ranch Core", 9.8, 2.4
elif mode == "Stonehenge (Wiltshire, UK)":
    user_lat, user_lon, target_name, base_imprint, tectonic_strain = 51.1789, -1.8262, "Stonehenge Stone Circle", 8.5, 1.1
elif mode == "The Great Pyramid (Giza, Egypt)":
    user_lat, user_lon, target_name, base_imprint, tectonic_strain = 29.9792, 31.1342, "Giza Pyramid Complex", 9.2, 1.5
elif mode == "The Paris Catacombs (Paris, France)":
    user_lat, user_lon, target_name, base_imprint, tectonic_strain = 48.8338, 2.3324, "Paris Subterranean Ossuary", 7.8, 1.0
else:
    st.sidebar.markdown("### 🗺️ Custom Coordinate Input")
    user_lat = st.sidebar.number_input("Target Latitude", value=0.0000, format="%.4f")
    user_lon = st.sidebar.number_input("Target Longitude", value=0.0000, format="%.4f")
    target_name = st.sidebar.text_input("Location Name Label", value="Custom Frequency Node")
    base_imprint = st.sidebar.slider("Historical Imprint Weight", 1.0, 10.0, 5.0)
    tectonic_strain = st.sidebar.slider("Tectonic Strain Factor", 1.0, 3.0, 1.0)

local_weather = get_localized_weather(user_lat, user_lon) if 'get_localized_weather' in globals() else {"temp_f": 65.0}

# --- NEW: RSPK POLTERGEIST AGENT VARIABLE ---
st.sidebar.header("👤 Recurrent Spontaneous Psychokinesis (RSPK)")
rspk_agent_stress = st.sidebar.slider(
    "Human Subconscious Stress Index",
    1.0, 10.0, 3.0,
    help="Models the electrical and neurological output spikes generated by a localized human mind under intense emotional compression."
)

st.sidebar.header("❤️ Emotional Coherence Alignment")
emotional_state = st.sidebar.selectbox(
    "Active Wave Coherence",
    ["Authenticity / Unconditional Love", "Baseline Awareness", "Fear / Contraction / Distortion"]
)

if emotional_state == "Fear / Contraction / Distortion":
    coherence_multiplier = 0.4
elif emotional_state == "Authenticity / Unconditional Love":
    coherence_multiplier = 4.5
else:
    coherence_multiplier = 1.0

# General Sliders
st.sidebar.header("⚡ Local Field Fluctuations")
rf_signal_16 = st.sidebar.slider("1.6 GHz RF Base Power (dBm)", -110, -30, -95)
seismic_hz = st.sidebar.slider("Micro-Seismic Resonance (Hz)", 0.0, 100.0, 5.0)

# --- SYSTEM ENGINE CALCULATIONS ---
# Calculate the total input catalyst compounding the RSPK human bio-output
rf_delta = max(0, (rf_signal_16 + 100) * 0.5)
seismic_delta = seismic_hz * 0.2
cosmic_flux = live_kp * 0.6 * lunar_grav

# The total environmental catalyst field combined with the RSPK stress variable
catalyst_field = rf_delta + seismic_delta + cosmic_flux + (rspk_agent_stress * 2.5)

# Calculate final output resonance incorporating Time Collapse mechanics
total_resonance = base_imprint * catalyst_field * tectonic_strain * (coherence_multiplier * 0.1)
prob_manifestation = 1 / (1 + np.exp(-0.11 * (total_resonance - 30)))

# State Classifications reflecting Space-Time Memory Alignment
if prob_manifestation > 0.90:
    field_state = "TIME COLLAPSE: Past & Present Residing Simultaneously (Maximum Resonance)"
elif total_resonance > 35.0:
    field_state = "HARMONIC ALIGNMENT: Subconscious RSPK Intersecting Environmental Geometry"
else:
    field_state = "EQUILIBRIUM: Stabilized Space-Time Frequency"

# Map Node Layout Setup
df_grid = pd.DataFrame([{
    "Location": target_name, "Lat": user_lat, "Lon": user_lon, 
    "Resonance": round(total_resonance, 2), "Probability": f"{round(prob_manifestation * 100, 1)}%", "State": field_state
}])

# --- USER INTERFACE LAYOUT ---
col1, col2 = st.columns(2)

with col1:
    st.subheader("📊 Universal Energy Grid Analytics")
    st.markdown(f"**Current Monitored Matrix Node:** `{target_name}`")
    
    m1, m2 = st.columns(2)
    m1.metric("Live Solar Kp-Index", f"{live_kp} / 9.0")
    m2.metric("Calculated Fluid Catalyst Field", round(catalyst_field, 2))
    
    st.dataframe(df_grid[["Location", "Resonance", "Probability", "State"]], use_container_width=True)
    
    # SYSTEM INTERPRETATION ANALYSIS
    st.info(f"""
    🔬 **Remote Analysis Matrix:** 
    Your model demonstrates that when the `Human Subconscious Stress Index (RSPK)` spikes to high levels, it introduces a massive energy vector into the room's environment. If the location possesses a dense historic record (like Giza or Stonehenge), the math maps a **TIME COLLAPSE**. The past and present overlap within the same geometric zone because the combined frequencies match the core source code of the grid.
    """)

with col2:
    st.subheader("🗺️ Global Target Coordinate Overlay")
    m = folium.Map(location=[user_lat, user_lon], zoom_start=15 if "Ranch" in target_name or "Stonehenge" in target_name else 14 if "Pyramid" in target_name else 12, tiles="OpenTopomap")
    
    marker_color = "red" if "COLLAPSE" in field_state else "orange" if "HARMONIC" in field_state else "blue"
    
    folium.Marker(
        location=[user_lat, user_lon],
        popup=f"<b>{target_name}</b><br>State: {field_state}",
        icon=folium.Icon(color=marker_color, icon="globe")
    ).add_to(m)
    
    folium.Circle(
        location=[user_lat, user_lon],
        radius=200,
        color="purple" if marker_color == "red" else "blue",
        fill=True,
        fill_opacity=0.15,
        popup="Calculated Geometric Resonance Radius"
    ).add_to(m)
    
    st_folium(m, width="100%", height=420, returned_objects=[])
